[Date]
date.timezone = "Asia/Tokyo" #タイムゾーンの指定

[mbstring] #文字に対する指定
default_charset = "UTF-8"
mbstring.language = "Japanese"

# エラーをブラウザに表示させる（開発中に便利です）
display_errors = On
display_startup_errors = On